Feature add metadata freshness
grnet/pysaml2 pull request #4
Opened 2019-10-15 14:06 UTC by nsklikas

Update documentation and remove unnecessary default value.

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [x] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

2019-10-15 15:12 UTC, NicolasLiampotis requested changes

2019-10-15 15:12 UTC, NicolasLiampotis commented on docs/howto/config.rst
> +When using MDQ the `freshness_period` option can be set, which is used to define
I would reword as follows: "When using MDQ, the `freshness_period` option can be set to define"

2019-10-15 15:12 UTC, NicolasLiampotis commented on docs/howto/config.rst
> +When using MDQ the `freshness_period` option can be set, which is used to define
Should we also describe what happens if `freshness_period` is not defined? Is there a default value or it means that metadata fetched using MDQ are valid forever?

2019-10-16 08:05 UTC, anange commented on docs/howto/config.rst
> +When using MDQ the `freshness_period` option can be set, which is used to define
> Should we also describe what happens if `freshness_period` is not defined? Is there a default value or it means that metadata fetched using MDQ are valid forever?
I agree, we should add something like "By default, the MDQ are valid forever, or until the app is restarted".

2019-10-16 12:09 UTC, nsklikas commented on docs/howto/config.rst
> +When using MDQ the `freshness_period` option can be set, which is used to define
Very well, I have updated the documentation. It should be OK now.

2019-10-16 12:10 UTC, NicolasLiampotis approved these changes
LGTM

2019-10-16 12:11 UTC, angelakis approved these changes

2019-10-16 13:37 UTC, merged